question_data = [
    {"response_code": 0,
     "results": [
         {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
          "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
          "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
          "question": "The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:",
          "correct_answer": "HD Graphics 500",
          "incorrect_answers": ["HD Graphics 700 ", "HD Graphics 600", "HD Graphics 7000"]},
         {"category": "Science: Computers",
          "type": "boolean",
          "difficulty": "easy",
          "question": "RAM stands for Random Access Memory.",
          "correct_answer": "True",
          "incorrect_answers": ["False"]},


         {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
          "question": "Which of these programming languages is a low-level language?",
          "correct_answer": "Assembly", "incorrect_answers": ["Python", "C#", "Pascal"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
          "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
          "question": "The numbering system with a radix of 16 is more commonly referred to as ",
          "correct_answer": "Hexidecimal",
          "incorrect_answers": ["Binary", "Duodecimal", "Octal"]},
         {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
          "question": "What does the term GPU stand for?",
          "correct_answer": "Graphics Processing Unit",
          "incorrect_answers": ["Gaming Processor Unit", "Graphite Producing Unit",
                                "Graphical Proprietary Unit"]},
         {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
          "question": "What is the main CPU is the Sega Mega Drive \/ Sega Genesis?",
          "correct_answer": "Motorola 68000",
          "incorrect_answers": ["Zilog Z80", "Yamaha YM2612", "Intel 8088"]},
         {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
          "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
          "correct_answer": "False", "incorrect_answers": ["True"]}]}
]
